name: Pipeline de Testes

on:
  push:

  workflow_dispatch:

  schedule:
    - cron: '0 12 * * *'

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: |
          mkdir -p reports
          npx mocha test/*.js \
          --reporter mocha-junit-reporter \
          --reporter-options mochaFile=reports/test-results.xml

      - name: Publicar relatório
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: reports/test-results.xml